package com.eps.sitemanager.dto;

import io.swagger.v3.oas.annotations.media.Schema;
import lombok.Data;

@Data
@Schema(description = "WLA Banc Master DTO")
public class WlaBancDTO {
	
	private int wlaBancId;
	private String epsSiteCode;
    private String siteType;
    private String siteSubtype;
    private String siteStatus;
    private String len;
    private String oldAtmId;
    private String atmId;
    private String locationName;
    private String district;
    private String address;
    private String state;
    private String city;
    private String pinCode;
    private String locationType;
    private String locationClass;
    private String latitude;
    private String longitude;
    private String landlordName;
    private String landlordNumber;
    private String cmName;
    private String cmContactNumber;
    private String rmName;
    private String rmContactNumber;
    private String stateHeadName;
    private String stateHeadNumber;
    private String masterFranchiseName;
    private String franchiseContactNumber;
    private String franchiseMailId;
    private String tisCategory;
    private String tisVendorName;
    private String tisRate;
    private String tisDoStatus;
    private String tisOrderDate;
    private String tisStartDate;
    private String tisEndDate;
    private String tisStatus;
    private String acMake;
    private String acCapacity;
    private String acStatus;
    private String upsVendor;
    private String upsOrderDate;
    private String upsBackupCapacityHrs;
    private String noOfBatteries;
    private String upsDeliveryDate;
    private String upsInstallationDate;
    private String upsInstallationStatus;
    private String itServoStabilizer;
    private String vsatType;
    private String vsatVendor;
    private String vsatOrderDate;
    private String vsatDeliveryDate;
    private String vsatId;
    private String vsatInstallationStatus;
    private String vsatCommissioningDate;
    private String hugsSubnet;
    private String siteBrandingVendor;
    private String siteBrandingType;
    private String siteBrandingOrderDate;
    private String signageInstallationDate;
    private String signageInstallationStatus;
    private String atmBrandingVendor;
    private String atmBrandingOrderDate;
    private String atmBrandingStatus;
    private String atmBrandingCompleteDate;
    private String eSurveillanceVendorName;
    private String eSurveillanceOrderDate;
    private String eSurveillanceDeliveryDate;
    private String eSurveillanceStatus;
    private String eSurveillanceCommissioningDate;
    private String atmVendor;
    private String atmModel;
    private String atmOrderDate;
    private String atmDeliveryDate;
    private String atmMachineSerialNo;
    private String sAndGLockNo;
    private String atmMachineStatus;
    private String techLiveDate;
    private String cashLiveDate;
    private String ejDocketNumber;
    private String tssDocketNo;
    private String lanIpAddress;
    private String atmIp;
    private String subnetMask;
    private String tlsDomainName;
    private String tcpPortNo;
    private String switchDestinationIp1;
    private String loadingType;
    private String craName;
    private String newLoadingType;
    private String finalRemarks;
}
